### ISSUE TITLE
Race condition in development mode

### ISSUE THREAD

**Issue by btc** [btc/recall#13]
in development environment at af6084d34333eb56c777187e9abe8aa660518939

"ArgumentError (A copy of SnapRepository has been removed from the module tree but is still active!):"

Caused by the SNAP_REPO initialized

perhaps replace with a singleton

**Comment by ukd1** [comment]
You got the backtrace for this?

**Comment by btc** [comment]
```
Started GET "/search?q=shout" for 127.0.0.1 at 2013-11-15 05:10:40 -0800
Processing by SnapController#search as HTML
  Parameters: {"q"=>"shout"}
Completed 500 Internal Server Error in 5ms

ArgumentError (A copy of SnapRepository has been removed from the module tree but is still active!):
  app/models/snap_repository.rb:23:in `engine'
  app/models/snap_repository.rb:12:in `find_with_text'
  app/controllers/snap_controller.rb:19:in `search'
```
